#+title: Library Management System
#+description: Project documentation for Computer
#+author: Saksham Sharma
#+SETUPFILE: export/setup/theme-darksun-local.setup
#+date: <2021-09-22 Wed>


*Name:* Library Management system

*Version:* 1.4

[[https://forthebadge.com/images/badges/60-percent-of-the-time-works-every-time.svg]] [[https://forthebadge.com/images/badges/0-percent-optimized.svg]] [[https://forthebadge.com/images/badges/designed-in-etch-a-sketch.svg]]


** Overview
Following is a document listing the features of a Library Management System that was built after being frustrated by the manual handling of data at the local library. The features include a system to manage a database of books, Students and Staff, and the ability to modify, sort and export relevant data.
The document also includes basic instructions if one wants to modify the program

** Objective

 + The table book contains information about all the books in the library: title, author's name, genre, number of pages and year of publication, rating, and how many books are available.
 + The student and staff tables include information about the employees who issue books and readers.
 + The operation table includes information about transactions that have occurred: who issued the book and to whom, and the date of issue (iss_date), as well as the planned return date (return_date) and the return indicator (return_indicator, issued — 0, returned — 1).
 + To Build a Library management system that is easy to use and provides a hassel free experience

- MySQL Database Hosted on [[https://clever-cloud.com/en/][Clever Cloud]] with IP Authentication
*** Releases
- Pre-Alpha:

** Features

*** Book Table
  - ID
  - ISBN Code
  - Book Name
  - Genre
  - Author
  - Book Year
  - Book Count
  - Book Page
  - Rank

*** Operation
  - ID
  - Student ID
  - Staff ID
  - Book ID
  - Issue Date
  - Return Date
  - Return Indicator

*** Student
  - ID
  - Full Name
  - Gender
  - Date of Birth

*** Staff
  - ID
  - Full Name
  - Gender
  -Date of Birth

*** Category, Publisher, Author
  - Names
  - List

** Future Prospects
- WebApp
- Integrate barcode scanning
- Ability to select local or cloud database

** Resources
*** Requirements

**** QtDesigner
If you want to edit the .ui files ie the actual LOOK or LAYOUT
+ [[https://build-system.fman.io/static/public/files/Qt%20Designer%20Setup.exe][Install on Windows]]
+ [[https://build-system.fman.io/static/public/files/Qt%20Designer.dmg][Install on Mac]]
+ *Installing on Linux (Debian and Fedora)*
 - [[https://flathub.org/apps/details/io.qt.QtCreator][Flatpak]]
 #+BEGIN_SRC bash
 sudo apt-get install qttools5-dev-tools qttools5-dev
 
 sudo dnf install qttools5-dev-tools qttools5-dev
 #+END_SRC

**** Python Dependencies
To install python dependencies use the =requirements.txt= file with python pip

*** Icon Manipulation:
Follow these steps to change hte programs icons
1. Keep the same name (for ease)
2. In the folder, open terminal and run the following code
   #+BEGIN_SRC bash
   pyrcc5 icons.qrc -o icons_rc.py
   #+END_SRC
